[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "cancun"          # safe subset of Arc's Osaka baseline
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]
fs_permissions = [{ access = "read-write", path = "./deployments" }]

[fmt]
line_length = 100
tab_width = 4

[rpc_endpoints]
arc_testnet = "https://rpc.testnet.arc.network"
hashkey_testnet = "https://hashkey-chain-testnet.rpc.thirdweb.com"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
